"""Remove patient_id from EEGFolder

Revision ID: 5b2e52e23efd
Revises: 87ef529591c5
Create Date: 2025-06-12 03:36:25.990331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b2e52e23efd'
down_revision = '87ef529591c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eeg_folders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('eeg_folders_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eeg_folder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'eeg_folders', ['eeg_folder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('eeg_folder_id')

    with op.batch_alter_table('eeg_folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('eeg_folders_ibfk_1'), 'patients', ['patient_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
