"""Add patient_id to EEGFile

Revision ID: 62badc402a10
Revises: a5f133f70668
Create Date: 2025-04-26 22:13:35.174079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62badc402a10'
down_revision = 'a5f133f70668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eeg_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eeg_files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###
