"""Add eeg_folder_id to patients

Revision ID: 6a2bdb2249d7
Revises: 6cedaa4664cf
Create Date: 2025-04-26 20:33:16.409640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2bdb2249d7'
down_revision = '6cedaa4664cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eeg_folder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'eeg_folders', ['eeg_folder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('eeg_folder_id')

    # ### end Alembic commands ###
