"""Create patients table

Revision ID: 6cedaa4664cf
Revises: f8f19fbe01f8
Create Date: 2025-04-23 15:30:34.394913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6cedaa4664cf'
down_revision = 'f8f19fbe01f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.alter_column('eeg_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('eeg_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'patient_states', ['state_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('patient_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eeg_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'eeg_files', ['eeg_id'], ['id'])

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('sex', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('sex')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('patient_states', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('eeg_id')

    with op.batch_alter_table('eeg_files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('state_id')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.alter_column('eeg_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
