"""Add eeg_folder_id to EEGFile

Revision ID: 87ef529591c5
Revises: bac5ad58c619
Create Date: 2025-06-12 03:24:36.819053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ef529591c5'
down_revision = 'bac5ad58c619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eeg_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eeg_folder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'eeg_folders', ['eeg_folder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eeg_files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('eeg_folder_id')

    # ### end Alembic commands ###
