"""Fix relationships between Patient, EEGFolder, and EEGFile

Revision ID: a5f133f70668
Revises: 6a2bdb2249d7
Create Date: 2025-04-26 21:44:45.918253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5f133f70668'
down_revision = '6a2bdb2249d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint('patients_ibfk_2', type_='foreignkey')
        batch_op.drop_column('eeg_folder_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eeg_folder_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('patients_ibfk_2', 'eeg_folders', ['eeg_folder_id'], ['id'])

    # ### end Alembic commands ###
