"""Updated models

Revision ID: b52ee0ef87ef
Revises: 62badc402a10
Create Date: 2025-06-12 02:13:11.485891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b52ee0ef87ef'
down_revision = '62badc402a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('patient_sex', sa.String(length=10), nullable=False))
        batch_op.alter_column('diagnosis',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('confidence_level',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('rhythm_analysis',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('analysis_reports_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('state_id')
        batch_op.drop_column('anomalies')

    with op.batch_alter_table('eeg_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('diagnosis', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('confidence_level', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rhythm_analysis', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('analyzed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('file_name',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('state_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['state_id'])
        batch_op.drop_constraint(batch_op.f('eeg_files_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('eeg_files_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('eeg_files_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'patient_states', ['state_id'], ['id'])
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('eeg_folder_id')

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_column('file')
        batch_op.drop_column('analysis')

    with op.batch_alter_table('patient_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspicion_level', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('symptoms', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('family_history', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('cognitive_score', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('motor_observation', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('speech_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('social_behavior', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('eeg_file_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('patient_states_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('patient_states_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'eeg_files', ['eeg_file_id'], ['id'])
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['id'])
        batch_op.drop_column('comments')
        batch_op.drop_column('stress_level')
        batch_op.drop_column('conditions')
        batch_op.drop_column('sleep_patterns')
        batch_op.drop_column('eeg_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eeg_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sleep_patterns', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('conditions', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('stress_level', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('comments', mysql.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('patient_states_ibfk_1'), 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('patient_states_ibfk_2'), 'eeg_files', ['eeg_id'], ['id'])
        batch_op.drop_column('eeg_file_id')
        batch_op.drop_column('social_behavior')
        batch_op.drop_column('speech_notes')
        batch_op.drop_column('motor_observation')
        batch_op.drop_column('cognitive_score')
        batch_op.drop_column('family_history')
        batch_op.drop_column('symptoms')
        batch_op.drop_column('suspicion_level')

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('file', mysql.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('eeg_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eeg_folder_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('eeg_files_ibfk_2'), 'patient_states', ['state_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('eeg_files_ibfk_1'), 'eeg_folders', ['eeg_folder_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('eeg_files_ibfk_3'), 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('state_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('file_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('analyzed_at')
        batch_op.drop_column('rhythm_analysis')
        batch_op.drop_column('confidence_level')
        batch_op.drop_column('diagnosis')
        batch_op.drop_column('uploaded_at')

    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anomalies', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('state_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('analysis_reports_ibfk_2'), 'patient_states', ['state_id'], ['id'])
        batch_op.alter_column('rhythm_analysis',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('confidence_level',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('diagnosis',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('patient_sex')
        batch_op.drop_column('patient_age')

    # ### end Alembic commands ###
