"""Fix Patient and PatientState relationship

Revision ID: bac5ad58c619
Revises: b52ee0ef87ef
Create Date: 2025-06-12 02:46:56.575322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bac5ad58c619'
down_revision = 'b52ee0ef87ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_states', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('patient_states_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('patient_states_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('eeg_file_id')
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('eeg_file_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('patient_states_ibfk_1'), 'eeg_files', ['eeg_file_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('patient_states_ibfk_2'), 'patients', ['patient_id'], ['id'])

    # ### end Alembic commands ###
