"""Add cascade delete to patient-related models

Revision ID: e0456f754efd
Revises: 35d6acc214b3
Create Date: 2025-06-12 12:01:49.600485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0456f754efd'
down_revision = '35d6acc214b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('analysis_reports_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'eeg_files', ['eeg_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('eeg_files', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('eeg_files_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('eeg_files_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('eeg_files_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'eeg_folders', ['eeg_folder_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'patient_states', ['state_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('patient_states', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('patient_states_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('patients_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('patients_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'eeg_folders', ['eeg_folder_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('patients_ibfk_2'), 'eeg_folders', ['eeg_folder_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('patients_ibfk_1'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('patient_states', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('patient_states_ibfk_1'), 'patients', ['patient_id'], ['id'])

    with op.batch_alter_table('eeg_files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('eeg_files_ibfk_2'), 'patients', ['patient_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('eeg_files_ibfk_3'), 'eeg_folders', ['eeg_folder_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('eeg_files_ibfk_1'), 'patient_states', ['state_id'], ['id'])

    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('analysis_reports_ibfk_1'), 'eeg_files', ['eeg_id'], ['id'])

    # ### end Alembic commands ###
